# 服务器端口
server:
  port: 8080
  servlet:
    context-path: /api
# 数据库设置
spring:
  data:
    mongodb:
      uri:  mongodb://root:123@localhost:27017
      database: xc_cms
  datasource:
    #1.JDBC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xc_course?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root

    initial-size: 5
    min-idle: 5
    max-active: 20
    #配置获取连接等待超时的时间
    max-wait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 30000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filter:
      stat:
        merge-sql: true
        slow-sql-millis: 5000

mybatis-plus:
  mapper-locations: classpath:/**/*Mapper.xml
  type-aliases-package: com.server.web
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

fdfs:
  tracker-list: 192.168.25.133:22122
  httpurl: http://192.168.25.133/

COURSE_BASE_URL: localhost:8080
